### PR TITLE
[TIMOB-18540] Tooling: Update versions of node.js in use on Travis

### PR DESCRIPTION
**Pull request by muhammaddadu**
[TIMOB-18540](https://jira.appcelerator.org/browse/TIMOB-18540)

### CODE REVIEW

**Comment by ingo** [comment]
@jhaynie Appears there is an issue with Node 12 here. Should we take a look?

**Comment by jhaynie** [comment]
if you can great, otherwise me or @alasdairhurst can fix it.

**Comment by ingo** [comment]
@muhammaddadu can you see if you can figure out the issue here?

**Comment by alasdairhurst** [comment]
While running the tests i came across the same issue as this: https://jira.appcelerator.org/browse/API-445
Looks like we were right about the logger not closing the file stream when exiting causing issues on Windows.

Removing this from the tests causes all tests to pass with Windows & node 0.12.
Also confirmed working on OSX node 0.12

Is there any way we can re-run the build?

**Comment by ingo** [comment]
This is no longer necessary.

**Pull request closed without merging**
